### ISSUE TITLE
Is the logic wrong there?

### ISSUE THREAD

**Issue by malaiwah** [gluster/gluster-prometheus#145]
See line 64 there: https://github.com/gluster/gluster-prometheus/blob/acbe4417b7723f37f740468dedff02a6d5f495ba/pkg/glusterutils/exporterd.go#L64

The loop goes on peerList, finds the first online peer and exits.
It exits with the leader status as true if the first peer ( [0] ) ID is the same as the local peer ID.
I guess the first in peerList is supposed to be the leader, so ... why loop?

A- Either the loop is useless (or is it an optimization (used like a condition) to skip over if there are no peers?)
B- Either this should be using the loop index instead of [0], or else we compare against a possibly offline peer?
C- Either the return statement should be removed so this falls to the other return at the end.

**Comment by sidharthanup** [comment]
@malaiwah The loop is required so as to find the first online peer. The return statement signifies that the particular peer/node is not the leader and hence should return false. Thanks for pointing it out because I have noticed a small error in the comparison logic. It should have been:
```
for _, pr := range peerList {
		if pr.Online {
			if peerID == pr.ID {
				return true, nil
			}
			return false, nil
		}
}
```
instead of : 
```
for _, pr := range peerList {
		if pr.Online {
			if peerID == peerList[0].ID {
				return true, nil
			}
			return false, nil
		}
}
```
Sending a PR to fix it. Hope this clears your confusion @malaiwah

**Comment by malaiwah** [comment]
> Sending a PR to fix it. Hope this clears your confusion @malaiwah

Thanks for the quick follow-up! Yes, all good.
